# Nombre del microservicio
spring.application.name=anuncio

# Inclusión de errores detallados en las respuestas de la API
spring.web.error.include-binding-errors=always
spring.web.error.include-message=always

# CORREGIDO: URL apuntando directamente a tu instancia AWS RDS
spring.datasource.url=jdbc:mysql://database-1.chantxslz5t9.us-east-1.rds.amazonaws.com:3306/db_anuncios?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=M4tt5_643224

# Estrategia de JPA/Hibernate (Actualiza tablas automáticamente en RDS sin borrar datos)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Puerto exclusivo del microservicio de Anuncios
server.port=4545