# Nombre del microservicio
spring.application.name=reservas
app.version=0.0.1-SNAPSHOT


spring.web.error.include-binding-errors=always
spring.web.error.include-message=always

spring.datasource.url=jdbc:mysql://database-1.chantxslz5t9.us-east-1.rds.amazonaws.com:3306/db_reservas?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=M4tt5_643224

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


server.port=8082